### ISSUE TITLE
Missing user.conf after installation/run

### ISSUE THREAD

**Issue by vladyslavtereshchuk** [bluppfisk/coinprice-indicator#77]
Hello @bluppfisk!

Could you please clarify where I can find user.conf, app work as expected but can't figure out how to save my preferences/assets after reboot needs to set up all again.

Thanks in advance!

**Comment by bluppfisk** [comment]
Hi. It should be in the project root folder (where run.sh is). I suspect you can just create one. If not, add something like below and store it there as user.conf.

```
max_decimals: 4
plugins:
- binance: true
- bitfinex: true
- bitstamp: true
- bittrex: true
- cexio: true
- gdax: true
- gemini: true
- hitbtc: true
- kraken: true
- okcoin: true
- poloniex: true
- unocoin: true
recent:
significant_digits: 2
tickers:
- asset_pair: XXBTZEUR
  default_label: cur
  exchange: kraken
  refresh: 3
```
